<?php
die;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

create database book_store;

CREATE TABLE `products` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `product_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_url` text COLLATE utf8mb4_unicode_ci,
  `category_paths` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mrp` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_description` text COLLATE utf8mb4_unicode_ci,
  `product_brand` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_available` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `discount` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


/*
-- Query: SELECT * FROM book_store.products
LIMIT 0, 500

-- Date: 2021-05-21 23:08
*/
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (1,'ELEFQZ6FBCSZR5XT','Target Publications MHT CET PCM (Physics Chemistry Maths) Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https ://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/5/x/t/2020-mht-cet-pcm-physics-chemistry-maths-online-test-series-2020-original-imafqz9xqeaafxsz.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/5/x/t/2020-mht-cet-pcm-physics-chemistry-maths-online-test-series-2020-original-imafqz9xqeaafxsz.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/5/x/t/2020-mht-cet-pcm-physics-chemistry-maths-online-test-series-2020-original-imafqz9xqeaafxsz.jpeg?q=90','Digital>E-learning>Online Courses','1000.0','1000.0','http => //www.flipkart.com/target-publications-mht-cet-pcm-physics-chemistry-maths-online-test-series-2020-preparation-1-year-subscription/p/itm033a3c561dbd1?pid=ELEFQZ6FBCSZR5XT&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET PCM i.e. Physics, Chemistry and Mathematics 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 72 Topic wise tests, 24 Revision Tests, 9 Unit Tests, 15 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt.','Target Publications','true','0','Flipkart',NULL,NULL);
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (2,'ELEFQZ5ZZVSATGJH','Target Publications MHT CET Biology Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/g/j/h/2020-mht-cet-biology-online-test-series-2020-preparation-1-year-original-imafqz9xjtfzzxpc.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/g/j/h/2020-mht-cet-biology-online-test-series-2020-preparation-1-year-original-imafqz9xjtfzzxpc.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/g/j/h/2020-mht-cet-biology-online-test-series-2020-preparation-1-year-original-imafqz9xjtfzzxpc.jpeg?q=90','Digital>E-learning>Online Courses','400.0','400.0','http => //www.flipkart.com/target-publications-mht-cet-biology-online-test-series-2020-preparation-1-year-subscription/p/itmbe86bed2822a3?pid=ELEFQZ5ZZVSATGJH&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET Biology 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 24 Topic wise tests, 8 Revision Tests, 3 Unit Tests, 5 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt.','Target Publications','true','0','Flipkart',NULL,NULL);
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (3,'ELEFQZ5ZK7HDJMHH','Target Publications MHT CET Physics Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/m/h/h/2020-mht-cet-physics-online-test-series-2020-preparation-1-year-original-imafqz9xapta2fju.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/m/h/h/2020-mht-cet-physics-online-test-series-2020-preparation-1-year-original-imafqz9xapta2fju.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/m/h/h/2020-mht-cet-physics-online-test-series-2020-preparation-1-year-original-imafqz9xapta2fju.jpeg?q=90','Digital>E-learning>Online Courses','400.0','400.0','http => //www.flipkart.com/target-publications-mht-cet-physics-online-test-series-2020-preparation-1-year-subscription/p/itmd6470cc0e4aeb?pid=ELEFQZ5ZK7HDJMHH&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET Physics 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 24 Topic wise tests, 8 Revision Tests, 3 Unit Tests, 5 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt.','Target Publications','true','0','Flipkart',NULL,NULL);
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (4,'ELEFQZ5ZTGHG3G5G','Target Publications MHT CET Maths Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/g/5/g/2020-mht-cet-maths-online-test-series-2020-preparation-1-year-original-imafqz9xkbhguu8h.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/g/5/g/2020-mht-cet-maths-online-test-series-2020-preparation-1-year-original-imafqz9xkbhguu8h.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/g/5/g/2020-mht-cet-maths-online-test-series-2020-preparation-1-year-original-imafqz9xkbhguu8h.jpeg?q=90','Digital>E-learning>Online Courses','400.0','400.0','http => //www.flipkart.com/target-publications-mht-cet-maths-online-test-series-2020-preparation-1-year-subscription/p/itmc42dcf10a6a84?pid=ELEFQZ5ZTGHG3G5G&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET Mathematics 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 24 Topic wise tests, 8 Revision Tests, 3 Unit Tests, 5 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt.','Target Publications','true','0','Flipkart',NULL,NULL);
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (5,'ELEFQZ5ZSYXVAPDA','Target Publications MHT CET Chemistry Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/p/d/a/2020-mht-cet-chemistry-online-test-series-2020-preparation-1-original-imafqz9xchgzgeqh.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/p/d/a/2020-mht-cet-chemistry-online-test-series-2020-preparation-1-original-imafqz9xchgzgeqh.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/p/d/a/2020-mht-cet-chemistry-online-test-series-2020-preparation-1-original-imafqz9xchgzgeqh.jpeg?q=90','Digital>E-learning>Online Courses','400.0','400.0','http => //www.flipkart.com/target-publications-mht-cet-chemistry-online-test-series-2020-preparation-1-year-subscription/p/itmec9d55988ce3f?pid=ELEFQZ5ZSYXVAPDA&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET Chemistry 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 24 Topic wise tests, 8 Revision Tests, 3 Unit Tests, 5 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt.','Target Publications','true','0','Flipkart',NULL,NULL);
INSERT INTO `` (`id`,`product_id`,`title`,`image_url`,`category_paths`,`mrp`,`price`,`product_url`,`product_description`,`product_brand`,`is_available`,`discount`,`platform`,`created_at`,`updated_at`) VALUES (6,'ELEFQZ5YHF7TFZM7','Target Publications MHT CET PCB (Physics Chemistry Biology) Online Test Series 2020 preparation (1 year subscription) Test Preparation(User ID-Password)','https://rukminim1.flixcart.com/image/200/200/k8q8nm80/e-learning/z/m/7/2020-mht-cet-pcb-physics-chemistry-biology-online-test-series-original-imafqz9xh5fkhfhd.jpeg?q=90;https => //rukminim1.flixcart.com/image/400/400/k8q8nm80/e-learning/z/m/7/2020-mht-cet-pcb-physics-chemistry-biology-online-test-series-original-imafqz9xh5fkhfhd.jpeg?q=90;https => //rukminim1.flixcart.com/image/800/800/k8q8nm80/e-learning/z/m/7/2020-mht-cet-pcb-physics-chemistry-biology-online-test-series-original-imafqz9xh5fkhfhd.jpeg?q=90','Digital>E-learning>Online Courses','1000.0','1000.0','http => //www.flipkart.com/target-publications-mht-cet-pcb-physics-chemistry-biology-online-test-series-2020-preparation-1-year-subscription/p/itmcd6e0a95af494?pid=ELEFQZ5YHF7TFZM7&affid=agarwalra1','Innovative learning is imperative for the future of education to help students reach their full potential. Target Publications Online Test Series for MHT-CET PCB i.e. Physics, Chemistry and Biology 2020 is our novel take on traditional learning. Its attributes make it an unparalleled tool for students who are poised to appear for MHT-CET examination. This test series comprises of 72 Topic wise tests, 24 Revision Tests, 9 Unit Tests, 15 Model Tests and Each test can be attempted only once per user. Accurate reports of a student performance with questions classified as correct, incorrect and not attempted in a bar graph and pie chart format are provided. Online Test Series gives students a tool to smartly manage their time and use their strengths to maximize their result. Note =>  Once your order is placed, it will take 0 to 24 hrs to create your account on our online test portal i.e. www.targetpublications.org/online-tests. Once the account is created, we will send the login credentials to your registered email id so that you can begin solving the tests. You can click on LOGIN (Online Test) to enter the credentials and begin your attempt','Target Publications','true','0','Flipkart',NULL,NULL);
